name: clashr-bin

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "clashr-bin.yaml"

jobs:
  aur-sync:
    runs-on: ubuntu-latest
    steps:
      - name: clashr-bin
        uses: maniaciachao/aur-sync-action@v1.2
        with:
          package_name: clashr-bin
          github_repo: "frainzy1477/clashrdev"
          commit_username: "Github Action Bot"
          commit_email: maniaciachao@gmail.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
