name: logisim-evolution

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "logisim-evolution.yaml"

jobs:
  aur-sync:
    runs-on: ubuntu-latest
    steps:
      - name: logisim-evolution
        uses: maniaciachao/aur-sync-action@v1.2
        with:
          package_name: logisim-evolution
          github_repo: "reds-heig/logisim-evolution"
          commit_username: "Github Action Bot"
          commit_email: maniaciachao@gmail.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          extra_dependencies: "jre-openjdk hicolor-icon-theme"
