name: logisim-ita-bin

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "logisim-ita-bin.yaml"

jobs:
  aur-sync:
    runs-on: ubuntu-latest
    steps:
      - name: logisim-ita-bin
        uses: maniaciachao/aur-sync-action@master
        with:
          package_name: logisim-ita-bin
          github_repo: "LogisimIt/Logisim"
          commit_username: "Github Action Bot"
          commit_email: maniaciachao@gmail.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          extra_dependencies: "jre-openjdk hicolor-icon-theme"
